apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-claim
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: ocs-storagecluster-ceph-rbd
